// Package grpc_user_server
// Code generated by gogenie-impl.
package grpc_user_server

import (
	"{{.ProjectName}}/proto"
	"{{.ProjectName}}/service"
)

var _ service.UserServer = &GrpcImpl{}

// @autowire(service.UserServer,set=grpc,skip=UnimplementedUserServer)
type GrpcImpl struct {
	proto.UnimplementedUserServer
}
