// Code generated by gogenie-http. DO NOT EDIT.
// Generate Hash: 0f05051176a2ab928e337b4a178f7bca
package clients

import (
	"context"
	"net/http"
	"time"

	"git.bestfulfill.tech/devops/go-core/implements/httpreq"
	"git.bestfulfill.tech/devops/go-core/interfaces/ihttp"
)

type Client struct {
	Client ihttp.Client
}

type ClientConfig struct {
	ClientHost string `json:"client_host"`
}

func NewClient(cfg ClientConfig) *Client {
	return &Client{
		Client: httpreq.NewJsonClient(cfg.ClientHost, func(cli *http.Client) {
			cli.Timeout = 30 * time.Second
		}),
	}
}

func (c Client) DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error) {
	ret, err = c.Client.Do(ctx, method, route, param)
	return
}
