// Code generated by gogenie-http. DO NOT EDIT.
// Generate Hash: fa53612c5f5879905f5b3350e4f87c14
package clients

import (
	"context"
)

type Client struct {
	Host string
}

func NewClient(host string) *Client {
	return &Client{Host: host}
}

func (c Client) DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error) {
	return
}
