// Package dao_operation_logs_dao
// Code generated by gogenie-impl.
package dao_operation_logs_dao

import dao "{{.ProjectName}}/dao"

var _ dao.OperationLogsDao = &DaoImpl{}

// @autowire(dao.OperationLogsDao,set=dao)
type DaoImpl struct {
}
