// Package svc_tools_service
// Code generated by gogenie-impl.
package svc_tools_service

import (
	"go-template/dao"
	"go-template/internal/database"
	"go-template/service"
)

var _ service.ToolsService = &Service{}

// @autowire(service.ToolsService,set=service)
type Service struct {
	SQL              database.Mysql
	OperationLogsDao dao.OperationLogsDao
}
