// Package svc_tools_service
// Code generated by gogenie-impl.
package svc_tools_service

import (
	"{{.ProjectName}}/dao"
	"{{.ProjectName}}/internal/database"
	"{{.ProjectName}}/service"
)

var _ service.ToolsService = &Service{}

// @autowire(service.ToolsService,set=service)
type Service struct {
	OperationLogsDao dao.OperationLogsDao `json:"operation_logs_dao"`
	Db               database.DB          `json:"db"`
}
