// Code generated by gogenie-http. DO NOT EDIT.
// Generate Hash: 2a5363b16b2d746d713327cae4dcffb1
package tools

import (
	svrlessgin "github.com/Just-maple/serverless-gin"
	"github.com/gin-gonic/gin"

	"go-template/service"
)

func RegisterToolsGroup(svc service.ToolsService, router gin.IRoutes, svcH svrlessgin.GinSvcHandler) {
	//
	router.GET("tools/ping", svcH(svc.Ping))

}
