// Code generated by gogenie-http. DO NOT EDIT.
// Generate Hash: 9b12d9aa0ea36e02514455153f673e3f
package tools

import (
	svrlessgin "github.com/Just-maple/serverless-gin"
	"github.com/gin-gonic/gin"

	"{{.ProjectName}}/service"
)

func RegisterToolsGroup(svc service.ToolsService, router gin.IRoutes, svcH svrlessgin.GinSvcHandler) {
	//
	router.GET("tools/ping", svcH(svc.Ping))

}
