// Code generated by gogenie-http. DO NOT EDIT.
// Generate Hash: 46a919dc1bc64f7297b35f9b8398bcca
package client_tools

import (
	"context"

	"{{.ProjectName}}/service"
)

var _ ToolsClient = &Client{}

type Client struct {
	baseClient interface {
		DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
	}
}

func NewClient(baseClient interface {
	DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
}) ToolsClient {
	return &Client{baseClient: baseClient}
}

type ToolsClient interface {
	DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
	//
	Ping(ctx context.Context, param service.PingParam) (ret string, err error)
}

func (c Client) DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error) {
	return c.baseClient.DoRequest(ctx, method, route, param, ret)
}

func (c Client) Ping(ctx context.Context, param service.PingParam) (ret string, err error) {
	err = c.DoRequest(ctx, "GET", "tools/ping",
		param, &ret)
	return
}
