// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/apis"

	"github.com/google/wire"
)

var WorkSet = wire.NewSet(
	wire.Struct(new(apis.WorkServices), "*"),
)
