// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/apis"
	"{{.ProjectName}}/internal/svc_impls/svc_middleware_service"
	"{{.ProjectName}}/internal/svc_impls/svc_user_service"
	"{{.ProjectName}}/service"

	"github.com/google/wire"
)

var ServiceSet = wire.NewSet(
	wire.Struct(new(apis.Services), "*"),

	wire.Struct(new(svc_middleware_service.Service), "*"),
	wire.Bind(new(service.MiddlewareService), new(*svc_middleware_service.Service)),

	wire.Struct(new(svc_user_service.Service), "*"),
	wire.Bind(new(service.UserService), new(*svc_user_service.Service)),
)
