// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
)

var Sets = wire.NewSet(
	ConfigSet,
	DaoSet,
	DbSet,
	GrpcSet,
	InitSet,
	ServiceSet,
)
