// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/apis"
	"{{.ProjectName}}/internal/svc_impls/svc_tools_service"
	"{{.ProjectName}}/service"
)

var ServiceSet = wire.NewSet(
	wire.Struct(new(apis.Services), "*"),

	wire.Struct(new(svc_tools_service.Service), "*"),
	wire.Bind(new(service.ToolsService), new(*svc_tools_service.Service)),
)
