// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/internal/sdks/clients/tools"
	"{{.ProjectName}}/internal/sdks/grpc_clients"

	"github.com/google/wire"
)

var ClientSet = wire.NewSet(
	tools.NewToolsClient,

	grpc_clients.NewGrpcClient,
)
