// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"go-template/apis"
	"go-template/internal/svc_impls/svc_tools_service"
	"go-template/service"

	"github.com/google/wire"
)

var ServiceSet = wire.NewSet(
	wire.Struct(new(apis.Services), "*"),

	wire.Struct(new(svc_tools_service.Service), "*"),
	wire.Bind(new(service.ToolsService), new(*svc_tools_service.Service)),
)
