// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/apis"
	"{{.ProjectName}}/internal/grpc_impls/grpc_user_server"
	"{{.ProjectName}}/service"
)

var GrpcSet = wire.NewSet(
	wire.Struct(new(apis.GrpcServices), "*"),

	wire.Struct(new(grpc_user_server.GrpcImpl)),
	wire.Bind(new(service.UserServer), new(*grpc_user_server.GrpcImpl)),
)
