// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/dao"
	"{{.ProjectName}}/internal/dao_impls/dao_operation_logs_dao"
)

var DaoSet = wire.NewSet(
	wire.Struct(new(dao_operation_logs_dao.DaoImpl), "*"),
	wire.Bind(new(dao.OperationLogsDao), new(*dao_operation_logs_dao.DaoImpl)),
)
