// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/config"
)

var ConfigSet = wire.NewSet(
	wire.FieldsOf(new(*config.Config), "DbConfig", "GrpcServerConfig", "MetricsGatewayConfig", "ServerConfig", "TracerConfig"),
)
