// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/internal/apps"
	"{{.ProjectName}}/internal/apps/grpc"
	"{{.ProjectName}}/internal/apps/server"
	"{{.ProjectName}}/internal/apps/worker"

	"github.com/google/wire"
)

var InitSet = wire.NewSet(
	wire.Struct(new(apps.BaseGrpcServer), "*"),

	wire.Struct(new(apps.BaseServer), "*"),

	wire.Struct(new(apps.BaseWorker), "*"),

	apps.InitGinServer,

	apps.InitGrpcServer,

	apps.InitMetricsPush,

	apps.InitTracer,

	apps.InitWorkerManager,

	wire.Struct(new(apps.Runtime), "*"),

	wire.Struct(new(grpc.GrpcServer), "*"),

	wire.Struct(new(server.Server), "*"),

	wire.Struct(new(worker.Worker), "*"),
)
