// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/internal/database"
)

var DbSet = wire.NewSet(
	database.InitKafkaClient,

	database.InitKafkaProducer,

	database.InitRedis,

	database.InitRedisCluster,

	database.InitSql,
)
