// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/config"

	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	wire.FieldsOf(new(*config.Config), "ClientConfig", "DbConfig", "GrpcClientConfig", "GrpcServerConfig", "MetricsGatewayConfig", "RedisConfig", "ServerConfig", "TracerConfig", "WorkerConfig"),
)
