// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"{{.ProjectName}}/dao"
	"{{.ProjectName}}/internal/dao_impls/dao_user_dao"

	"github.com/google/wire"
)

var DaoSet = wire.NewSet(
	wire.Struct(new(dao_user_dao.DaoImpl), "*"),
	wire.Bind(new(dao.UserDao), new(*dao_user_dao.DaoImpl)),
)
