// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"{{.ProjectName}}/apis"
	"{{.ProjectName}}/config"
	"{{.ProjectName}}/internal/apps"
	"{{.ProjectName}}/internal/apps/server"
	"{{.ProjectName}}/internal/apps/worker"
	"{{.ProjectName}}/internal/dao_impls/dao_operation_logs_dao"
	"{{.ProjectName}}/internal/database"
	"{{.ProjectName}}/internal/svc_impls/svc_tools_service"
)

// Injectors from wire.gen.go:

func InitializeServer(c0 *config.Config) (*server.Server, func(), error) {
	gatewayConfig := c0.MetricsGatewayConfig
	gatewayDaemon, cleanup := apps.InitMetricsPush(gatewayConfig)
	jaegerConfig := c0.TracerConfig
	tracer, cleanup2, err := apps.InitTracer(jaegerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runtime := apps.Runtime{
		MetricsPushDaemon: gatewayDaemon,
		Tracer:            tracer,
	}
	engine := apps.InitGinServer()
	baseServer := apps.BaseServer{
		Runtime: runtime,
		Engine:  engine,
	}
	serverConfig := c0.ServerConfig
	daoImpl := &dao_operation_logs_dao.DaoImpl{}
	dbConfig := c0.DbConfig
	db, cleanup3, err := database.InitSql(dbConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service := &svc_tools_service.Service{
		OperationLogsDao: daoImpl,
		Db:               db,
	}
	services := apis.Services{
		ToolsService: service,
	}
	serverServer := &server.Server{
		BaseServer:   baseServer,
		ServerConfig: serverConfig,
		Services:     services,
	}
	return serverServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitializeWorker(c0 *config.Config) (*worker.Worker, func(), error) {
	daoImpl := &dao_operation_logs_dao.DaoImpl{}
	dbConfig := c0.DbConfig
	db, cleanup, err := database.InitSql(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	service := &svc_tools_service.Service{
		OperationLogsDao: daoImpl,
		Db:               db,
	}
	services := apis.Services{
		ToolsService: service,
	}
	gatewayConfig := c0.MetricsGatewayConfig
	gatewayDaemon, cleanup2 := apps.InitMetricsPush(gatewayConfig)
	jaegerConfig := c0.TracerConfig
	tracer, cleanup3, err := apps.InitTracer(jaegerConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := apps.Runtime{
		MetricsPushDaemon: gatewayDaemon,
		Tracer:            tracer,
	}
	workerManager := apps.InitWorkerManager()
	baseWorker := apps.BaseWorker{
		Runtime:       runtime,
		WorkerManager: workerManager,
	}
	workerWorker := &worker.Worker{
		Services:   services,
		BaseWorker: baseWorker,
	}
	return workerWorker, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
