// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"github.com/google/wire"
	"{{.ProjectName}}/config"
	"{{.ProjectName}}/internal/apps/grpc"
	"{{.ProjectName}}/internal/apps/server"
	"{{.ProjectName}}/internal/apps/worker"
)

func InitializeGrpcServer(c0 *config.Config) (*grpc.GrpcServer, func(), error) {
	panic(wire.Build(Sets))
}

func InitializeServer(c0 *config.Config) (*server.Server, func(), error) {
	panic(wire.Build(Sets))
}

func InitializeWorker(c0 *config.Config) (*worker.Worker, func(), error) {
	panic(wire.Build(Sets))
}
