// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"go-template/apis"
	"go-template/config"
	"go-template/internal/apps"
	"go-template/internal/apps/server"
	"go-template/internal/apps/worker"
	"go-template/internal/dao_impls/dao_operation_logs_dao"
	"go-template/internal/database"
	"go-template/internal/svc_impls/svc_tools_service"
)

// Injectors from wire.gen.go:

func InitializeServer(c0 *config.Config) (*server.Server, func(), error) {
	mysqlConfig := c0.MysqlConfig
	mysql, cleanup, err := database.InitSql(mysqlConfig)
	if err != nil {
		return nil, nil, err
	}
	daoImpl := &dao_operation_logs_dao.DaoImpl{}
	service := &svc_tools_service.Service{
		SQL:              mysql,
		OperationLogsDao: daoImpl,
	}
	services := apis.Services{
		ToolsService: service,
	}
	gatewayConfig := c0.MetricsGatewayConfig
	gatewayDaemon, cleanup2 := apps.InitMetricsPush(gatewayConfig)
	jaegerConfig := c0.TracerConfig
	tracer, cleanup3, err := apps.InitTracer(jaegerConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := apps.Runtime{
		MetricsPushDaemon: gatewayDaemon,
		Tracer:            tracer,
	}
	engine := apps.InitGinServer()
	baseServer := apps.BaseServer{
		Runtime: runtime,
		Engine:  engine,
	}
	kserverConfig := c0.ServerConfig
	serverServer := &server.Server{
		Services:   services,
		BaseServer: baseServer,
		Config:     kserverConfig,
	}
	return serverServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitializeWorker(c0 *config.Config) (*worker.Worker, func(), error) {
	mysqlConfig := c0.MysqlConfig
	mysql, cleanup, err := database.InitSql(mysqlConfig)
	if err != nil {
		return nil, nil, err
	}
	daoImpl := &dao_operation_logs_dao.DaoImpl{}
	service := &svc_tools_service.Service{
		SQL:              mysql,
		OperationLogsDao: daoImpl,
	}
	services := apis.Services{
		ToolsService: service,
	}
	gatewayConfig := c0.MetricsGatewayConfig
	gatewayDaemon, cleanup2 := apps.InitMetricsPush(gatewayConfig)
	jaegerConfig := c0.TracerConfig
	tracer, cleanup3, err := apps.InitTracer(jaegerConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := apps.Runtime{
		MetricsPushDaemon: gatewayDaemon,
		Tracer:            tracer,
	}
	workerManager := apps.InitWorkerManager()
	baseWorker := apps.BaseWorker{
		Runtime:       runtime,
		WorkerManager: workerManager,
	}
	workerWorker := &worker.Worker{
		Services:   services,
		BaseWorker: baseWorker,
	}
	return workerWorker, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
