// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package internal

import (
	"go-template/config"
	"go-template/internal/apps/server"
	"go-template/internal/apps/worker"

	"github.com/google/wire"
)

func InitializeServer(c0 *config.Config) (*server.Server, func(), error) {
	panic(wire.Build(Sets))
}

func InitializeWorker(c0 *config.Config) (*worker.Worker, func(), error) {
	panic(wire.Build(Sets))
}
