// Code generated by gogenie-db2struct. DO NOT EDIT.
// Generate Hash: 2aace8db4adb885c06b4c15e6932ca50
//
//go:generate gogenie db2struct operation_logs
package table

import "time"

// operation_logs :
type OperationLogs struct {
	// 日志ID
	Id int `gorm:"column:id;primaryKey;type:integer;not null" json:"id"`
	// 操作类型
	OperationType string `gorm:"column:operation_type;type:text;not null" json:"operation_type"`
	// 表名
	Name string `gorm:"column:name;type:text;not null" json:"name"`
	// 记录ID
	RecordId int `gorm:"column:record_id;type:integer;not null" json:"record_id"`
	// IP地址
	IpAddress string `gorm:"column:ip_address;type:text;not null" json:"ip_address"`
	// 用户代理
	UserAgent string `gorm:"column:user_agent;type:text;not null" json:"user_agent"`
	// 创建时间
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;autoCreateTime" json:"created_at"`
}

const TableOperationLogs = "operation_logs"

func (o *OperationLogs) TableName() string {
	return TableOperationLogs
}

type OperationLogsSlice []OperationLogs

func (this OperationLogsSlice) ForEach(f func(index int, t *OperationLogs)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this OperationLogsSlice) Filter(f func(t *OperationLogs) bool) OperationLogsSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(OperationLogsSlice, 0, len(this))
	this.ForEach(func(_ int, t *OperationLogs) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type OperationLogsIntMap map[int]*OperationLogs

func (this OperationLogsIntMap) ForEach(f func(key int, t *OperationLogs)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OperationLogsSlice) MapInt(mapFunc func(*OperationLogs) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *OperationLogs) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OperationLogsSlice) GroupInt(mapFunc func(*OperationLogs) int) (
	ret map[int]OperationLogsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]OperationLogsSlice)
	this.ForEach(func(_ int, t *OperationLogs) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OperationLogsSlice) ToIntMap(indexBy func(t *OperationLogs) int) (
	m OperationLogsIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OperationLogsIntMap)
	this.ForEach(func(_ int, t *OperationLogs) {
		m[indexBy(t)] = t
	})
	return m
}

type OperationLogsStringMap map[string]*OperationLogs

func (this OperationLogsStringMap) ForEach(f func(key string, t *OperationLogs)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OperationLogsSlice) MapString(mapFunc func(*OperationLogs) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *OperationLogs) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OperationLogsSlice) GroupString(mapFunc func(*OperationLogs) string) (
	ret map[string]OperationLogsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]OperationLogsSlice)
	this.ForEach(func(_ int, t *OperationLogs) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OperationLogsSlice) ToStringMap(indexBy func(t *OperationLogs) string) (
	m OperationLogsStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OperationLogsStringMap)
	this.ForEach(func(_ int, t *OperationLogs) {
		m[indexBy(t)] = t
	})
	return m
}
